{% set name = "django-linear-migrations" %}
{% set version = "2.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_linear_migrations-{{ version }}.tar.gz
  sha256: 29ce3710e1334494d5bcc8b707bde0253e1eacc5a8bf163d7234c88fe3493242

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - django >=3.2

test:
  imports:
    - django_linear_migrations
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/adamchainz/django-linear-migrations
  summary: Ensure your migrations are linear.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
